name: Build and deploy Node.js app to Azure Web App - reto3oath

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Empaquetar TODO el repo (raíz con el nuevo package.json)
      - name: Create zip
        run: |
          mkdir -p artifact
          zip -r artifact/app.zip . -x ".git/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_50FCDD6249D648FA9491458BE6B1459C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1907D44350904634A154718A7D652FCB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3B8045F7F0C84B32BEEED281268D4274 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reto3oath'
          slot-name: 'Production'
          package: artifact/app.zip
