name: Build and deploy Node.js app to Azure Web App - reto3oath

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: private/package-lock.json

      # Instalar deps en /private y generar Prisma (quedarán dentro del ZIP)
      - name: Install deps & prisma generate (server)
        working-directory: ./private
        run: |
          npm ci
          npx prisma generate

      - name: Build (if present)
        working-directory: ./private
        run: npm run build --if-present

      # 👉 Empaquetar TODO el repo en un ZIP (incluye private/node_modules)
      - name: Create deployment zip
        run: |
          mkdir -p artifact
          zip -r artifact/app.zip . -x ".git/*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: artifact/app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_50FCDD6249D648FA9491458BE6B1459C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1907D44350904634A154718A7D652FCB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3B8045F7F0C84B32BEEED281268D4274 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'reto3oath'
          slot-name: 'Production'
          package: artifact/app.zip
